spring:
  application:
    name: stant
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/stant
    username: postgres
  jackson:
    serialization:
          fail-on-empty-beans:
           false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
